# Generated by Django 3.1.6 on 2021-03-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='event date')),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('latitude', models.FloatField(default=41.7429795162564)),
                ('longitude', models.FloatField(default=111.809492111206)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('latitude', models.FloatField(default=41.7429795162564)),
                ('longitude', models.FloatField(default=111.809492111206)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.event')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotType', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('spots', models.IntegerField(default=1)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('account_balance', models.FloatField(default=100.0)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_attendant', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('attendant_for', models.ManyToManyField(to='apis.ParkingLot')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.IntegerField(default=0)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.parkingspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user'),
        ),
    ]
