# Generated by Django 3.1.6 on 2021-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attendant_for',
            field=models.ManyToManyField(blank=True, to='apis.ParkingLot'),
        ),
    ]
