# Generated by Django 3.1.7 on 2021-03-24 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0002_auto_20210318_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.FloatField(default=100.0)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_attendant', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('attendant_for', models.ManyToManyField(blank=True, to='apis.ParkingLot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.profile'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
