# Generated by Django 3.1.7 on 2021-03-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20210328_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=-111.809492111206),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(default=-111.809492111206),
        ),
    ]
