# Generated by Django 3.1.7 on 2021-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20210329_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='event',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='event',
            field=models.ManyToManyField(to='apis.Event'),
        ),
    ]
