# Generated by Django 3.1.7 on 2021-04-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20210410_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='spots',
            new_name='currentEventAvailableSpots',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='totalSpots',
            field=models.IntegerField(default=1),
        ),
    ]
