# Generated by Django 3.1.6 on 2021-04-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_reservation_checked_in'),
        ('apis', '0007_auto_20210410_1619'),
    ]

    operations = [
    ]
