# Generated by Django 3.1.7 on 2021-04-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_merge_20210410_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.event')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.parkinglot')),
            ],
        ),
    ]
